### ISSUE TITLE
.swc file

### ISSUE THREAD

**Issue by vump** [foo123/as3-transitions-lib#1]
Hello Nikos,

The SWC file is missing from your repository.
In the manual, you speak of the SWC that would include everything, but I cannot find it anywhere.

Or could you include the modified library files?

Thank you!

**Comment by foo123** [comment]
i dont use that project any more, but i have backup. Added all files i found and were in a publishable form (even the incomplete flash IDE components based on the  library), including a (obfuscated) `.swc` build of library (and any modified dependencies, i.e `PageFlip` and `Rippler`)

i will leave this issue open for a while if anything else is needed
