### ISSUE TITLE
Hello Nikos, images are at 0,0, how to change that?

### ISSUE THREAD

**Issue by xiaobuxun** [foo123/as3-transitions-lib#2]
I have a question about the position of the image, because I try some examples from your manual.pdf, I found when the transition start, the image will always in x:0 and y:0. if there is a solution to controll the position of image?

**Comment by foo123** [comment]
i'm not sure i understand what you mean. A transition is just a container with the initial/final/transition images inside that. In a sense they are all always at 0,0. You can simply position the whole transition container. Posting example code would help to be clear about this.

**Comment by xiaobuxun** [comment]
Thanks for responts, use your suggestion, it is works.Thanks very much.
